"""
main.py — ResearchPilot entry point (GitHub Models edition)

Usage:
    python main.py "What are the latest breakthroughs in fusion energy?"
    python main.py          ← interactive prompt
"""
from __future__ import annotations

import sys
from datetime import datetime
from pathlib import Path

from dotenv import load_dotenv
load_dotenv()

from rich.console import Console
from rich.markdown import Markdown
from rich.panel import Panel
from rich.rule import Rule

from agents import FinalReport
from orchestrator import run_pipeline

console = Console()


def to_markdown(r: FinalReport) -> str:
    lines = [
        f"# {r.title}",
        "",
        f"> **Confidence:** {r.confidence:.0%}",
        "",
        "## Executive Summary",
        "",
        r.summary,
        "",
    ]
    for s in r.sections:
        lines += [f"## {s['heading']}", "", s["body"], ""]
    if r.sources:
        lines += ["## Sources", ""]
        for src in r.sources:
            lines.append(f"- {src}")
        lines.append("")
    lines.append(
        f"---\n*Generated by ResearchPilot (GitHub Models) on "
        f"{datetime.now().strftime('%Y-%m-%d %H:%M')}*"
    )
    return "\n".join(lines)


def display(r: FinalReport) -> None:
    console.print(Rule(style="purple"))
    console.print(Panel(
        f"[bold]{r.title}[/bold]\n\nConfidence: [cyan]{r.confidence:.0%}[/cyan]",
        title="ResearchPilot — Final Report",
        border_style="purple",
    ))
    console.print(Markdown(to_markdown(r)))


def save(r: FinalReport, query: str) -> Path:
    slug = query[:40].lower().replace(" ", "_").replace("/", "-").strip("_")
    path = Path(f"report_{slug}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md")
    path.write_text(to_markdown(r), encoding="utf-8")
    return path


def main() -> None:
    if len(sys.argv) > 1:
        query = " ".join(sys.argv[1:])
    else:
        console.print(
            "[bold purple]ResearchPilot[/bold purple] — "
            "Powered by GitHub Models (free)\n"
        )
        query = console.input("[bold]Enter your research query:[/bold] ").strip()
        if not query:
            console.print("[red]No query provided.[/red]")
            sys.exit(1)

    report = run_pipeline(query)
    display(report)
    saved = save(report, query)
    console.print(f"\n[green]✓[/green] Saved → [bold]{saved}[/bold]")


if __name__ == "__main__":
    main()
